<a href="https://colab.research.google.com/github/dlopezuj/TFM_getrificacion_BCN/blob/main/Union_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Realizamos la unión de los dataframes

In [ ]:
# importamos librerías
import pandas as pd

In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
# realizamos la lectura de todos los archivos
union_natalidad = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Evolucion_demografica/output_evolucion_demografica/union_natalidad.csv")
union_jovenes = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Evolucion_demografica/output_evolucion_demografica/union_jovenes.csv")
union_ocupacion_media = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Evolucion_demografica/output_evolucion_demografica/union_ocupacion.csv")
union_migracion = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Evolucion_demografica/output_evolucion_demografica/union_migracion.csv")
union_densidad = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_demografica/output_evolucion_demografica/union_densidad.csv')
#
union_renta_media = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Evolucion_economica/output_evolucion_economica/union_renta_media.csv")
union_alquiler_medio = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Evolucion_economica/output_evolucion_economica/union_alquiler_medio.csv")
union_precio_medio = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Evolucion_economica/output_evolucion_economica/union_precio_medio.csv")
#
union_transporte = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_servicios/output_evolucion_servicios/union_transporte.csv')
union_cultura = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_servicios/output_evolucion_servicios/union_cultura.csv')
union_restaurantes = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_servicios/output_evolucion_servicios/union_restaurantes.csv')
union_parques = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_servicios/output_evolucion_servicios/union_parques.csv')
union_hoteles = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_servicios/output_evolucion_servicios/union_hoteles.csv')
#
union_criminalidad = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_social/output_evolucion_social/union_incidentes.csv')
union_universitarios = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Evolucion_social/output_evolucion_social/union_universitarios.csv')

Join de los Dataframes

In [ ]:
df_union_all = union_natalidad.set_index(['Codi_Barri','Any']) \
.join(union_jovenes.set_index(['Codi_Barri','Any'])) \
.join(union_ocupacion_media.set_index(['Codi_Barri','Any'])) \
.join(union_migracion.set_index(['Codi_Barri','Any'])) \
.join(union_densidad.set_index(['Codi_Barri','Any'])) \
.join(union_renta_media.set_index(['Codi_Barri','Any'])) \
.join(union_alquiler_medio.set_index(['Codi_Barri','Any'])) \
.join(union_precio_medio.set_index(['Codi_Barri','Any'])) \
.join(union_transporte.set_index(['Codi_Barri','Any'])) \
.join(union_cultura.set_index(['Codi_Barri','Any'])) \
.join(union_restaurantes.set_index(['Codi_Barri','Any'])) \
.join(union_parques.set_index(['Codi_Barri','Any'])) \
.join(union_hoteles.set_index(['Codi_Barri','Any'])) \
.join(union_criminalidad.set_index(['Codi_Barri','Any'])) \
.join(union_universitarios.set_index(['Codi_Barri','Any'])) \
.sort_values(by=['Codi_Barri','Any']).reset_index()
df_union_all

,Codi_Barri,Any,Tasa_natalidad_mil_hab,jovenes,Ocupacion_media(personas_domicilio),Tasa_migracion_mil_hab,Densitat neta (hab/ha),renta_media_hogar(euros),Alquiler_medio(Euros/m2 mes),precio_vivienda_Euros/m2,transporte,cultura,restaurantes,Parques,Hoteles,incidentes,Estudios_superiores
0,1,2015,9.1,11365,2.84,113.2,949,23379.571429,10.9975,2807.075,21.0,21.0,89.0,7.0,44.0,1739.0,9018
1,1,2016,9.6,11213,2.81,105.5,948,23866.761905,12.2700,2807.075,21.0,21.0,94.0,7.0,45.0,1740.0,9315
2,1,2017,10.5,11508,2.81,113.4,959,24383.952381,13.8950,3602.200,21.0,22.0,106.0,7.0,45.0,1725.0,10042
3,1,2018,9.3,11536,2.77,121.4,946,25485.809524,14.0175,4063.175,21.0,23.0,110.0,8.0,46.0,1569.0,10591
4,1,2019,9.1,12028,2.49,125.9,955,26815.904762,14.3250,3561.300,172.0,23.0,135.0,8.0,47.0,2189.0,11185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,73,2015,7.8,3622,2.51,38.0,717,30052.666667,8.9900,1795.525,5.0,0.0,2.0,0.0,0.0,148.0,2923
361,73,2016,8.2,3566,2.51,35.1,714,30739.095238,9.1225,1795.525,5.0,0.0,2.0,0.0,0.0,189.0,3144
362,73,2017,7.9,3551,2.51,43.2,716,30945.809524,10.1650,2083.500,5.0,0.0,2.0,0.0,0.0,165.0,3306
363,73,2018,6.6,3624,2.51,40.0,720,31907.428571,11.1450,2293.950,5.0,0.0,2.0,0.0,0.0,139.0,3485
364,73,2019,6.1,3596,2.45,43.3,721,33282.714286,11.4750,2476.325,23.0,0.0,2.0,0.0,0.0,187.0,3649

In [ ]:
# visualizamos los resultados
df_union_all.head(50)

,Codi_Barri,Any,Tasa_natalidad_mil_hab,jovenes,Ocupacion_media(personas_domicilio),Tasa_migracion_mil_hab,Densitat neta (hab/ha),renta_media_hogar(euros),Alquiler_medio(Euros/m2 mes),precio_vivienda_Euros/m2,transporte,cultura,restaurantes,Parques,Hoteles,incidentes,Estudios_superiores
0,1,2015,9.1,11365,2.84,113.2,949,23379.571429,10.9975,2807.075,21.0,21.0,89.0,7.0,44.0,1739.0,9018
1,1,2016,9.6,11213,2.81,105.5,948,23866.761905,12.2700,2807.075,21.0,21.0,94.0,7.0,45.0,1740.0,9315
2,1,2017,10.5,11508,2.81,113.4,959,24383.952381,13.8950,3602.200,21.0,22.0,106.0,7.0,45.0,1725.0,10042
3,1,2018,9.3,11536,2.77,121.4,946,25485.809524,14.0175,4063.175,21.0,23.0,110.0,8.0,46.0,1569.0,10591
4,1,2019,9.1,12028,2.49,125.9,955,26815.904762,14.3250,3561.300,172.0,23.0,135.0,8.0,47.0,2189.0,11185
5,2,2015,6.4,4147,2.36,142.2,454,26896.555556,11.2900,4255.375,13.0,5.0,103.0,1.0,44.0,2064.0,5255
6,2,2016,6.2,4329,2.44,140.7,457,27044.111111,13.0100,4255.375,13.0,5.0,111.0,1.0,51.0,1747.0,5462
7,2,2017,6.7,4620,2.48,167.2,471,27260.000000,14.1900,4528.850,13.0,5.0,115.0,1.0,52.0,1269.0,5734
8,2,2018,7.5,5077,2.59,206.3,492,28267.555556,13.7725,5226.725,13.0,5.0,118.0,1.0,54.0,1115.0,5914
9,2,2019,6.7,6050,2.79,253.6,546,30316.444444,14.2750,5067.000,110.0,5.0,151.0,2.0,57.0,1680.0,6414
10,3,2015,6.5,3535,2.20,103.3,1149,23761.181818,16.3325,4160.150,15.0,1.0,62.0,2.0,5.0,936.0,3399
11,3,2016,6.1,3598,2.20,103.0,1113,24206.363636,18.2125,4160.150,15.0,1.0,66.0,2.0,5.0,774.0,3502
12,3,2017,6.7,3792,2.19,117.2,1107,24598.454545,19.8450,4505.025,15.0,1.0,70.0,2.0,5.0,1060.0,3763
13,3,2018,5.6,3774,2.15,114.1,1088,25867.000000,16.9175,4923.550,15.0,1.0,75.0,2.0,5.0,671.0,3887
14,3,2019,5.7,4043,2.90,130.4,1097,27120.090909,17.4000,4884.000,95.0,1.0,86.0,2.0,5.0,682.0,4190
15,4,2015,7.3,5707,2.26,113.6,695,26178.461538,12.7400,3677.250,21.0,9.0,82.0,2.0,17.0,525.0,7482
16,4,2016,7.7,5810,2.25,106.5,689,27142.000000,14.0600,3677.250,21.0,9.0,90.0,2.0,19.0,524.0,7573
17,4,2017,7.9,5999,2.26,121.6,700,27412.615385,15.7050,4580.150,21.0,9.0,94.0,2.0,19.0,574.0,8172
18,4,2018,6.5,5887,2.21,127.1,686,29068.000000,15.0225,5256.475,21.0,10.0,104.0,2.0,20.0,535.0,8244
19,4,2019,6.3,6214,2.18,132.8,697,30888.538462,15.1750,4419.775,145.0,11.0,130.0,2.0,23.0,562.0,8725
20,5,2015,7.5,5539,2.46,63.5,944,37344.500000,10.8925,3792.425,19.0,6.0,17.0,6.0,10.0,929.0,10099
21,5,2016,8.0,5542,2.48,62.9,948,37836.450000,11.7400,3792.425,19.0,6.0,17.0,7.0,10.0,1083.0,10290
22,5,2017,7.2,5659,2.50,69.8,959,38720.100000,13.0850,4320.400,19.0,6.0,19.0,7.0,10.0,1171.0,10733
23,5,2018,8.4,5649,2.50,75.5,953,40134.550000,13.1425,4643.675,19.0,6.0,21.0,7.0,10.0,1027.0,11004
24,5,2019,6.3,5850,2.26,95.1,962,41890.550000,14.0000,4946.525,137.0,6.0,27.0,7.0,10.0,861.0,11450
25,6,2015,7.6,8882,2.35,63.9,995,36138.294118,11.2025,2896.650,13.0,4.0,35.0,6.0,2.0,1172.0,15568
26,6,2016,7.7,8967,2.35,61.4,1002,36530.323529,12.1900,2896.650,13.0,4.0,36.0,6.0,4.0,1114.0,15957
27,6,2017,7.5,9086,2.36,69.6,1006,37014.794118,13.3325,3615.075,13.0,4.0,36.0,8.0,4.0,1360.0,16581
28,6,2018,7.4,9219,2.35,74.2,1002,38589.235294,13.7175,3934.175,13.0,4.0,40.0,8.0,4.0,1499.0,17250
29,6,2019,7.0,9527,2.55,79.8,1003,40190.970588,14.4750,4241.625,127.0,4.0,54.0,8.0,4.0,1490.0,17964
30,7,2015,9.0,7309,2.37,68.2,382,47118.965517,11.2250,3538.950,33.0,10.0,145.0,12.0,62.0,3137.0,18609
31,7,2016,8.3,7447,2.38,67.4,383,48566.137931,12.8325,3538.950,33.0,11.0,155.0,12.0,72.0,2768.0,18849
32,7,2017,7.8,7568,2.39,72.6,387,48726.034483,13.5025,4654.200,33.0,12.0,169.0,12.0,76.0,3113.0,19420
33,7,2018,7.7,7627,2.37,75.3,382,50300.620690,13.9600,4444.125,33.0,12.0,189.0,12.0,80.0,3344.0,19631
34,7,2019,7.7,7898,2.36,86.6,382,53165.551724,14.4000,5018.950,326.0,12.0,264.0,12.0,89.0,2862.0,20166
35,8,2015,8.0,7607,2.31,70.4,622,42124.730769,11.3800,3914.200,14.0,4.0,140.0,9.0,25.0,888.0,16701
36,8,2016,7.7,7621,2.31,69.5,625,42638.461538,12.6650,3914.200,14.0,4.0,151.0,9.0,27.0,947.0,16788
37,8,2017,8.0,8059,2.33,81.9,631,43671.307692,13.6825,4256.650,14.0,4.0,157.0,10.0,27.0,962.0,17491
38,8,2018,7.7,8162,2.33,86.0,630,45818.076923,14.0475,4571.600,14.0,4.0,174.0,10.0,28.0,973.0,17950
39,8,2019,7.2,8595,2.38,94.3,633,47510.423077,14.4750,4897.100,157.0,4.0,248.0,10.0,28.0,953.0,18645
40,9,2015,7.7,10123,2.35,61.4,876,40483.250000,11.1300,3298.300,22.0,2.0,35.0,9.0,15.0,690.0,20005
41,9,2016,7.8,10125,2.35,60.4,883,41219.775000,12.3500,3298.300,22.0,2.0,36.0,9.0,15.0,669.0,20490
42,9,2017,7.9,10441,2.37,69.8,891,41767.625000,13.5025,4302.750,22.0,2.0,38.0,9.0,15.0,698.0,21367
43,9,2018,7.3,10570,2.36,67.5,889,43444.325000,13.9050,4028.675,22.0,2.0,39.0,9.0,15.0,672.0,22061
44,9,2019,7.4,10755,2.36,74.9,891,44836.350000,14.5000,4311.100,178.0,2.0,62.0,11.0,16.0,717.0,22938
45,10,2015,8.7,6818,2.33,60.3,917,35108.958333,10.8275,3000.375,20.0,5.0,49.0,7.0,10.0,574.0,11352
46,10,2016,7.2,6774,2.33,56.2,924,35974.083333,12.0650,3000.375,20.0,5.0,51.0,7.0,14.0,613.0,11539
47,10,2017,7.8,6798,2.34,64.9,928,36603.916667,12.9475,3349.075,20.0,5.0,58.0,7.0,14.0,570.0,12053
48,10,2018,8.8,6811,2.34,69.3,924,37814.041667,13.1675,4115.850,20.0,5.0,70.0,7.0,14.0,513.0,12393
49,10,2019,7.6,7019,2.36,77.6,925,40029.208333,13.8750,4274.700,99.0,5.0,92.0,7.0,14.0,588.0,12918

In [ ]:
# revisamos si hay valores null
df_union_all.isna().any()

Codi_Barri                             False
Any                                    False
Tasa_natalidad_mil_hab                 False
jovenes                                False
Ocupacion_media(personas_domicilio)    False
Tasa_migracion_mil_hab                 False
Densitat neta (hab/ha)                 False
renta_media_hogar(euros)               False
Alquiler_medio(Euros/m2 mes)           False
precio_vivienda_Euros/m2               False
transporte                             False
cultura                                False
restaurantes                           False
Parques                                False
Hoteles                                False
incidentes                             False
Estudios_superiores                    False
dtype: bool

## Escritura de datos a csv

In [ ]:
df_union_all.to_csv('/content/gdrive/MyDrive/Colab Notebooks/output/df_union_factores.csv', index = False)